steps:

- id: go_test
  name: "gcr.io/cloud-builders/go"
  args: ["test","./etapa3/*.go"]
  env:
    - 'GOPATH=./'

- id: go_build
  name: "gcr.io/cloud-builders/go"
  args: ["build","./etapa3/app.go"]

- id: deploying_app
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - './etapa3/app.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'

- id: deploying_mysql
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - './etapa2/'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'

- id: deploying_nginx
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - './etapa1/'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=my-first-cluster-1'
