apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeting-app
spec:
  selector:
    matchLabels:
      app: greeting-app

  template:
    metadata:
      labels:
        app: greeting-app
    spec:
      containers:
        - name: greeting-app
          image: jocajunior77/curso-code-desafio-k8s:latest
          ports:
            - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: greeting-service-app
  labels:
    app: greeting-service-app
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8000
  selector:
    app: greeting-app
