apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-k8s
  template:
    metadata:
      labels:
        app: nginx-k8s
    spec:
      containers:
        - image: nginx:1.16.0-alpine
          name: nginx
          command: ["/bin/sh","-c","mkdir -p /var/www/public; echo 'Code.education Rocks' > /var/www/public/index.html; nginx -g 'daemon off;'"]
          ports:
            - containerPort: 80