apiVersion: v1
kind: Service
metadata:
  name: nginx-service-k8s
  labels:
    app: nginx-service-k8s
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: nginx-k8s